language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install tox-travis

script:
  - tox
  - coverage run --source icon_font_to_png -m py.test
  - coverage report -m

after_success:
  - coveralls
