version: '2'
services:
  php:
    build:
      context: .
      dockerfile: compose/php/Dockerfile
    ports:
      - "80:80"
    volumes:
      - "./:/app/"
    command: /app/run.sh
    working_dir: /app/
